lawsyn/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from lawsyn import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('rzadach', views.rzadach, name='rzadach'),
    path('reshebniki', views.reshebniki, name='reshebniki'),
    path('razrab', views.razrab, name='razrab'),
    path('ychebnik', views.ychebnik, name='ychebnik'),
    path('sbor', views.sbor, name='sbor'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('registration', views.registration, name='registration'),
    path('TextSave', views.TextSave, name='TextSave'),
    path('userHelp', views.userHelp, name='userHelp'),
    path('add_to_favorites/<int:book_id>/', views.add_to_favorites, name='add_to_favorites'),
    path('remove_from_favorites/<int:book_id>/', views.remove_from_favorites, name='remove_from_favorites'),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class categories(models.Model):
    name = models.CharField('Категория', max_length=100, unique=True)

    class Meta:
        db_table = 'categories'
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name
    
class ychebniki(models.Model):
    author = models.CharField('Автор', max_length=150)
    description = models.TextField('Описание', blank=True, null=True)
    img = models.ImageField('Изображение', upload_to='images', blank=True, null=True)
    pdf_file = models.FileField(upload_to='pdf', blank=True, null=True)
    category = models.ForeignKey(to=categories, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.author
    
    class Meta:
        db_table = 'ychebniki'
        verbose_name = 'Учебник'
        verbose_name_plural = 'Учебники'

        
class User(AbstractUser):
    text = models.TextField('Заметки', blank=True, null=True)

    def __str__(self):
        return self.username
    
    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'


class Favorite(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    book = models.ForeignKey(to=ychebniki, on_delete=models.CASCADE)

class Help(models.Model):
    name = models.TextField('Имя', max_length=150, blank=True, null=True)
    email = models.TextField('Почта', max_length=150, blank=True, null=True)
    topik = models.TextField('Тема', max_length=150, blank=True, null=True)
    HelpText = models.TextField('Текст сообщения', blank=True, null=True)

    class Meta:
        db_table = 'Help'
        verbose_name = 'Обратная связь'
        verbose_name_plural = 'Обратная связь'

    

main/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from main.models import User, Help

class UserLoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()

class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            "username",
            "password1",
            "password2",
        )
    
    username = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

class UserInputForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['text',]

    text = forms.CharField()

class HelpInputForm(forms.ModelForm):

    class Meta:
        model = Help
        fields = ('name','email','topik','HelpText')

main/views.py
from pyexpat.errors import messages
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import auth
from django.urls import reverse
from main.forms import HelpInputForm, UserInputForm, UserLoginForm, UserRegistrationForm
from main.models import Favorite, ychebniki, User
from django.contrib.auth.decorators import login_required

def home(request):
    if request.user.is_authenticated:
        favorite_books = Favorite.objects.filter(user=request.user)
        data = {'favorite_books': favorite_books,}
        return render(request, 'main/home.html', data)
    else:
        return render(request, 'main/home.html')

def rzadach(request):
    try:
        text_obj=User.objects.get(id=request.user.id)
        text1 = text_obj.text
    except:
        text1=''

    if request.user.is_authenticated:
        favorite_books = Favorite.objects.filter(user=request.user)
        data = {'text1': text1,
                'favorite_books': favorite_books,}
        return render(request, 'main/rzadach.html', data)
    else:
        data = {'text1': text1,}
        return render(request, 'main/rzadach.html',data)

def reshebniki(request):

    if request.user.is_authenticated:
        favorite_books = Favorite.objects.filter(user=request.user)
        data = {'favorite_books': favorite_books,}
        return render(request, 'main/reshebniki.html', data)
    else:
        return render(request, 'main/reshebniki.html')

def razrab(request):
    if request.user.is_authenticated:
        favorite_books = Favorite.objects.filter(user=request.user)
        data = {'favorite_books': favorite_books,}
        return render(request, 'main/razrab.html', data)
    else:
        return render(request, 'main/razrab.html')

def ychebnik(request):
    if request.user.is_authenticated:
        favorite_books = Favorite.objects.filter(user=request.user)
        sbornik = ychebniki.objects.filter(category__name='Учебник')
        data = {'sbornik': sbornik,
                'favorite_books': favorite_books,}
        return render(request, 'main/ychebniki.html', data)
    else:
        sbornik = ychebniki.objects.filter(category__name='Учебник')
        data = {'sbornik': sbornik,}
        return render(request, 'main/ychebniki.html', data)

def sbor(request):
    if request.user.is_authenticated:
        favorite_books = Favorite.objects.filter(user=request.user)
        sbornik = ychebniki.objects.filter(category__name='Сборник')
        data = {'sbornik': sbornik,
                'favorite_books': favorite_books,}
        return render(request, 'main/sbor.html', data)
    else:
        sbornik = ychebniki.objects.filter(category__name='Сборник')
        data = {'sbornik': sbornik,}
        return render(request, 'main/sbor.html', data)

def registration(request):

    formReg = UserRegistrationForm(data=request.POST)
    url = request.META.get('HTTP_REFERER')

    if request.method == 'POST':
        formReg = UserRegistrationForm(data=request.POST)
        if formReg.is_valid():
            formReg.save()
            user = formReg.instance
            auth.login(request, user)
            return redirect(url)
        
    data = {'formReg': formReg,}
    return render(request, 'main/home.html', data)

def login(request):

    form = UserLoginForm(data=request.POST)
    url = request.META.get('HTTP_REFERER')

    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            User = auth.authenticate(username=username, password=password)
            if User:
                auth.login(request, User)
                return redirect(url)
            
    data = {'form': form,}
    return render(request, 'main/home.html', data)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('home'))

def TextSave(request):
    form = UserInputForm(request.POST, instance=request.user)
    url = request.META.get('HTTP_REFERER')
    try:
        text_obj=User.objects.get(id=request.user.id)
        text1 = text_obj.text
    except:
        text1=' '

    if request.method == 'POST':
        form = UserInputForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect(url)
        
    data = {'form': form,
            'text1': text1}
    return render(request, 'main/rzadach.html', data)

def add_to_favorites(request, book_id):
    url = request.META.get('HTTP_REFERER')
    if request.user.is_authenticated:
        book = get_object_or_404(ychebniki, id=book_id)
        Favorite.objects.get_or_create(user=request.user, book=book)
        return redirect(url)  # Замените на ваш URL
    else:
        return redirect(url)
    
def remove_from_favorites(request, book_id):
    url = request.META.get('HTTP_REFERER')
    if request.user.is_authenticated:
        book = Favorite.objects.get(id=book_id)
        book.delete()
        return redirect(url)
    else:
        return redirect(url)
    
@login_required
def userHelp(request):

    url = request.META.get('HTTP_REFERER')

    if request.method == 'POST':
        form = HelpInputForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect(url)
    else:
        form = HelpInputForm(request.POST, instance=request.user)
        
    data = {'form': form,}
    return render(request, 'main/razrab.html', data)

    

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Lawsyn - мир физики</title>
    <link rel="icon" type="image/x-icon" href="{% static "main/img/logo.jpg" %}">
    <link rel="stylesheet" href="{% static "main/css/home.css" %}">
</head>
<body>
    <div id="wrapper">
        <div class="up">
            <div class="link">
                <ul class="ulx">
                    <li class="active"><a href="{% url "home" %}">Lawsyn - для вас</a></li>
                    <li style="float: left;"><a href="{% url "rzadach" %}"> Решение задач</a></li>
                    <li style="float: left;"><a href="{% url "reshebniki" %}">Пособия</a>
                    <li style="float: right;"><a href="{% url "razrab" %}">О нас</a></li>
                    {% if user.is_authenticated %}
                        <li style="float: right;">
                            <a href="{% url 'logout' %}" class="exit">Выход из аккаунта</a>
                        <li/>
                        <li style="float: right;">
                            <a onclick="showCart()" class="exit">Избранное</a>
                        <li/>
                    {% else %}
                        <li style="float: right;">
                            <a onclick="showLogin()" class="loginBtn">Вход в аккаунт</a>
                        <li/>
                    {% endif %}
                </ul>
            </div>
        </div>  
    </div>
    <form id="cart_items_container" class="modal">
        <div class="modal-content">
            <span class="close" onclick="closeCart()"></span>
                <div class="headName">Избранное</div>
                <div id="cart_items">
                    {% if favorite_books %}
                        {% for favorite in favorite_books %}
                            <ul>
                                <li>
                                    <h2><b>{{ favorite.book.author }} - {{ favorite.book.description }}</b><h2>
                                    <a href="{{ favorite.book.pdf_file.url }}">
                                        <img src="{{ favorite.book.img.url }}" alt="Ошибка" style="width:100px;height: 150px">
                                    </a>
                                    <a href="{% url 'remove_from_favorites' favorite.id %}">Удалить из избранного</a>
                                </li>
                            </ul>
                        {% endfor %}
                    {% else %}
                        <p style="font-size: 1em">В избранном ничего нет(</p>
                    {% endif %}
                    
                </div>
        </div>
    </form>

    <form action="{% url 'login' %}" method="post" id="loginModal" class="modal">
        <div class="modal-content">
            <div class="close" onclick="closeLogin()"></div>
            <div class="headName">Вход в аккаунт</div>
            <div class="field-holdeer">
                <label for="id_username" class="form-label login">Имя пользователя</label>
                <input type="text" class="form-control login"
                value="{% if form.username.value %}{{ form.username.value }}{% endif %}" 
                name="username" id="id_username" required>
            </div>
            <div class="field-holdeer">
                <label for="id_password" class="form-label login">Пароль</label>
                <input type="password" class="form-control login" 
                value="{% if form.password.value %}{{ form.password.value }}{% endif %}" 
                name="password" id="id_password" required>
            </div>
            <button class="enterLogin">Войти</button>
            {% csrf_token %}

            {% if form.non_field_errors %}
                <p id="ErrorForm">{{ form.non_field_errors }}</p>
            {% endif %}

            <div id="downRegistr">Нет аккаунта?
                <a onclick="showReg()" class="loginBtn">Зарегистрироваться</a>
            </div>
        </div>
    </form>

    <form action="{% url 'registration' %}" method="post" id="registerModal" class="modal">
        <div class="modal-content">
            <div class="close" onclick="closeReg()"></div>
            <div class="headName">Регистрация</div>
            <div class="field-holdeer">
                <label for="id_username1" class="form-label login">Имя пользователя</label>
                <input type="text" class="form-control login"
                name="username" id="id_username1" required
                readonly onfocus="this.removeAttribute('readonly')">
            </div>
            {% if user.is_authenticated %}
            {% else %}
                {% if formReg.username.errors %}
                    <p id="ErrorForm2">{{ formReg.username.errors }}</p>
                {% endif %}
            {% endif %}

            <div class="field-holdeer">   
                <label for="id_password1" class="form-label login">Пароль</label>
                <input type="password" class="form-control login" id="id_password1" 
                    name="password1" required>
            </div>

            {% if user.is_authenticated %}
            {% else %}
                {% if formReg.password1.errors %}
                    <p id="ErrorForm2">{{ formReg.password1.errors }}</p>
                {% endif %}
            {% endif %}

            <div class="field-holdeer">
                <label for="id_password2" class="form-label login">Подтверждение пароля</label>
                <input type="password" class="form-control login" id="id_password2"
                    name="password2" required>
            </div>
            
            {% if user.is_authenticated %}
            {% else %}
                {% if formReg.password2.errors %}
                    <p id="ErrorForm2">{{ formReg.password2.errors }}</p>
                {% endif %}
            {% endif %}

            {% if user.is_authenticated %}
            {% else %}
            {% if formReg.non_field_errors %}
                <p id="ErrorForm2">{{ formReg.non_field_errors }}</p>
            {% endif %}
            {% endif %}
                
            <button class="enterLogin">Продолжить</button>
            {% csrf_token %}
            <div id="downRegistr">Есть аккаунт?
                <a onclick="showLogin()" class="loginBtn">Войти</a>
            </div>
        </div>
    </form>
    {% block content %}{% endblock %}
    <div id="down">
        <ul id="down">
            <li style="float: right; color: white"  >Авторское право 2022-2023. Все права защищены.</li>
        </ul>
    </div>
    <script src="{% static 'main/js/main.js' %}"></script>
</body>
</html>

main/templates/main/home.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}    
    <div id="main">
        <br>
        <br>
        <div id="box" onmouseover="spin();"></div>
    </div>
    <br>
    <div>
        <p align="center" style="font-size: 270%" ><b>Физика</b></p>
        <img class="centers" src="{% static "main/img/sfera.png" %}" alt="Ошибка загрузки" width="300px" height="300px">
    </div>
    
    <div class="physblock">
        <h4 class="physblock">Физика — область естествознания: наука о наиболее общих законах природы, о материи, её структуре, движении и правилах трансформации. Простыми словами, Физика - это все что нас окруажет. Понятия физики и её законы лежат в основе всего естествознания. Является точной наукой.</h4>
    </div>
    <br>
    <br>
    <br>
    <p align="center" style="font-size: 270%" ><b>Что даст вам наш сайт?</b></p>
        <img class="center" src={% static "main/img/chel.jpg" %} alt="Ошибка загрузки" width="300px" height="300px">
    <h4 class="physblock">Lawsyn - даст вам максимальное количество информации во всей сфере физики. Мы предоставляем вам учебники и сборники задач используемые во всех уголках страны. Наши калькулятор решит все ваши потребности. При помощи Lawsyn вы можете легко найти нужную вам физическую величину и узнать о ней.</h4>
    <br>
    <br>
    <br>  
    <p align="center" style="font-size: 270%"><b>Часто задавыаемые вопросы</b></p>
    <img class="center" src={% static "main/img/vopros.jpg" %} alt="Ошибка загрузки" width="300px" height="300px">
    <h4 class="physblock">Частые вопросы, которые возникают:
        <br>
    -Возможно ли выучить всю физику на нашем сайте?
        <br>
    -Правильно ли записаны и расписаны физические величины?
        <br>
    -Возможно ли сдать экзамен использую Lawsyn?
        <br>
    Мы ответим вам - да! Наш сайт предоставит всю нужную информацию по изучению такого предмета как физика.
    </h4>
    <br>
    <br>
    <br>
    <p align="center" style="font-size: 270%" ><b>Почему именно Lawsyn?</b></p>
        <img class="center" src={% static "main/img/mi.jpg" %} alt="Ошибка загрузки" width="300px" height="300px">
    <h4>Почему именно Lawsyn должен стать вашим путеводителем по физике? Мы дадим вам ответ
        <br>
    -Наш сайт был создан совсем не давно, а это значит, что он являеется актулаьным &#10004;
        <br>
    -Lawsyn был специализирован конкретно на физике и ни на чем больше &#10004;
        <br>
    -Мы отсеяли все лишние и не нужные источники информации &#10004;
        <br>
    -Наш сайт был сделан максимально простым и приятным в использовании &#10004;
        <br>    
    </h4>
    <br>    
    <br>    
    <br>    
{% endblock  %}

main/templates/main/razrab.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}    
    <div id="main">
        <br>
        <br>
        <br>
        <p align="center" style="font-size: 270%"><b> Возникли проблемы с сайтом?</b></p>
        <img class="center" src={% static "main/img/error.png" %} alt="Ошибка загрузки" width="500px" height="300px">
        <h4 class="physblock">Если вы заметили неправильную работу сайта или опечатки/ошибки в информации, вы можете отправить обращение, которое мы обязательно рассмотрим и решим вашу проблему.
             <br>
        </h4>
        <h4>    
        -Просим по возможности умещать все проблемы в одну отправку.
             <br>    
        -Будьте терпеливее, возможно возник большой сбой, в котором мы уже разбираемся.
        </h4>    
        <br>
        <br>
        <div class="fr">
            {% if user.is_authenticated %}
                <form action="{% url 'userHelp' %}" method="post" id="form_message" align="center" >
                    <h2>Форма для связи с нами:</h2>
                    <br>
                    
                    <div class="titles">Ваше имя*</div>
                    <input name="name" id="id_name" value="">
                    
                    <div class="titles">Электронная почта*</div>
                    <input name="email" id="id_email" value=" ">
                    
                    <div class="titles">Тема сообщения*</div>
                    <input  name="topik" id="id_topik" value=" ">
                    
                    <div class="titles">Текст сообщения:*</div>
                    <input name="HelpText" id="id_HelpText" value=" ">
                    
                    {% if form.email.errors %}
                    <ul class="errorlist nonfield" id="ErrorForm4">
                        {% for field in form %}
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    {% csrf_token %}
                    <h1><button id="submit" type="submit">Отправить</button></h1> 
                </form>
            {% else %}
            {% endif %}
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>    
{% endblock  %}

main/templates/main/reshebniki.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}    
    <div id="main">
        <br>
        <br>
        <br>
        <p align="center" style="font-size: 180%"><b> Тут вы можете ознакомиться с полным выбором имеющих учебников и сборников.</b></p>
            <img class="center" src={% static "main/img/book.jpg" %} alt="Ошибка загрузки" width="500px" height="300px">
        <h4>Выберите что вы хотите открыть:</h4>
        <br>
        <br>
        <br>
        <br>
        <div class="btn"> 
            <a href="{% url "ychebnik" %}"><button class="button button2">Учебники</button></a>
            <a href="{% url "sbor" %}"><button class="button button2">Сборники</button></a>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock  %}    

main/templates/main/sbor.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}    
    <div id="main">
        <h4>Ниже вы можете ознакомиться с полным списком сборников задач.</h4>
        <p align="center" style="font-size: 170%"> Выберите нужный вам сборник:</p>
        {% for ychebnik in sbornik %}
          <div class="card">
              <a href="{{ ychebnik.pdf_file.url }}">
              <img src="{{ ychebnik.img.url }}" alt="Ошибка" style="width:300px;height: 400px">
              <div class="container">
                <h2><b>{{ ychebnik.description }}</b><h2> 
                <h3>{{ ychebnik.author }}</h3> 
                {% if user.is_authenticated %}
                <a align="center" style="font-size: 30px"
                href="{% url 'add_to_favorites' ychebnik.id %}">
                <p style="font-size: 30px">Добавить в избранное</p></a>
                {% else %}
                {% endif %}
              </div>
          </div>
        {% endfor %}       
    </div>
{% endblock  %}

main/templates/main/ychebniki.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}    
    <div id="main">
        <h4>Ниже вы можете ознакомиться с полным списком учебников.</h4>
            <p align="center" style="font-size: 170%"> Выберите нужный вам учебник:</p>
        {% for ychebnik in sbornik %}
          <div class="card">
              <a href="{{ ychebnik.pdf_file.url }}">
              <img src="{{ ychebnik.img.url }}" alt="Ошибка" style="width:300px;height: 400px">
              <div class="container">
                <h2><b>{{ ychebnik.description }}</b><h2> 
                <h3>{{ ychebnik.author }}</h3> 
                {% if user.is_authenticated %}
                <a align="center" style="font-size: 30px"
                href="{% url 'add_to_favorites' ychebnik.id %}">
                <p style="font-size: 30px">Добавить в избранное</p></a>
                {% else %}
                {% endif %}
              </div>
          </div>
        {% endfor %}         
    </div>
    <br>
    <br>
    <br>
    <br>
{% endblock  %}